spring:
  application:
    name: pizzaria-service
  datasource:
    url: jdbc:h2:mem:pizzadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
pizzaria:
  entregas:
    queue: ${PIZZARIA_ENTREGAS_QUEUE:pizzaria.entregas}
