spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: pizzaria-service
              uri: lb://pizzaria-service
              predicates:
                - Path=/,/cardapio/**,/clientes/**,/pedidos/**,/relatorios/**,/admin/**,/h2/**
              filters:
                - PreserveHostHeader
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
security:
  jwt:
    secret: ${JWT_SECRET:chave-de-seguranca-pizzaria-precisa-de-muitos-caracteres}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
